---
**Task 1.** У тебе є дані по користувачу за два дні:

- **День 1**: вектор `v1 = (перегляди, лайки, коментарі) = (10, 3, 1)`
- **День 2**: `v2 = (7, 5, 0)`

In [1]:
import numpy as np

v1 = np.array([10, 3, 1])
v2 = np.array([7, 5, 0])

# use operation + in numpy 
# code

res = v1 + v2
print(res)


[17  8  1]


---
Task 1.1 
Дані
У користувача є активність за 3 дні:

- День 1 → `v1 = (12 переглядів, 3 лайки, 1 коментар)`
- День 2 → `v2 = (20, 5, 0)`
- День 3 → `v3 = (8, 2, 1)`

In [2]:
import numpy as np

v1 = np.array([12, 3, 1])
v2 = np.array([20, 5, 0])
v3 = np.array([8, 2, 1])

# use operation + in numpy 
# code
print(v1 + v2 + v3)

[40 10  2]


---
**Task 2.** Є два користувачі зі схожого сегменту:

> u1 = (перегляди, лайки, підписки) = (30, 4, 1) \
> u2 = (20, 6, 0)

Потрібно зрозуміти, чим відрізняється їхня поведінка.

In [3]:
import numpy as np

u1 = np.array([30, 4, 1])
u2 = np.array([20, 6, 0])

# use operation - in numpy
# code
print(u1 - u2)

[10 -2  1]


---
**Task 2.2**
Поведінка користувача за 2 тижні:

Тиждень 1 → w1 = (100 переглядів, 15 лайків, 3 підписки)

Тиждень 2 → w2 = (140, 18, 5)

In [4]:
import numpy as np

w1 = np.array([100, 15, 3])
w2 = np.array([140, 18, 5])

# use operation - in numpy

print(w2-w1)

[40  3  2]


---
**Task 3.1**  З’ясувати, хто “сильніший” за загальною активністю.

Два користувачі: \
u1 = (50 переглядів, 10 лайків, 4 підписки) \
u2 = (70, 5, 1)



In [5]:
import numpy as np

u1 = np.array([50, 10, 4])
u2 = np.array([70, 5, 1])

# use linalg.norm

print(np.linalg.norm(u1), np.linalg.norm(u2))

51.146847410177685 70.18546858146635


---
**Task 4.** Двоє користувачів у просторі ознак:

> u1 = (перегляди, лайки) = (10, 2) \
> u2 = (15, 5)

Потрібно:
> знайти відстань між ними (евклідова), \
> зрозуміти, хто “активніший” у загальному масштабі.

In [6]:
# 1. Відстань між користувачами
u1 = np.array([10, 2])
u2 = np.array([15, 5])
# use np.linalg.norm
# code 
print(np.linalg.norm(u1 - u2))

# 2. Рівень активності кожного (довжина вектора)
# use np.linalg.norm
# code 
print(np.linalg.norm(u1), np.linalg.norm(u2))


5.830951894845301
10.198039027185569 15.811388300841896


---
**Task 5.** Нормалізація поведінкових фіч перед кластеризацією


In [7]:
import numpy as np

users = np.array([
    [10, 3, 1],
    [40, 2, 0],
    [20, 5, 2],
    [15, 1, 1],
    [60, 7, 3]
])

# use linalg.norm
# users / by previos step
norms = np.linalg.norm(users, axis=1, keepdims=True)
users_normalized = users / norms
print(users_normalized)


[[0.95346259 0.28603878 0.09534626]
 [0.99875234 0.04993762 0.        ]
 [0.9656091  0.24140227 0.09656091]
 [0.99558497 0.06637233 0.06637233]
 [0.99204049 0.11573806 0.04960202]]


---
**Task 5.** Оцініть наскільки користувачу підходить товар

In [8]:
# user data 
#u = (0.2, 0.8, 0.3, 0.1)

# product data
#p = (0.25, 0.75, 0.2, 0.15)


import numpy as np

u = np.array([0.2, 0.8, 0.3, 0.1])
m = np.array([0.25, 0.75, 0.2, 0.15])

score = np.dot(u,m) / (np.linalg.norm(u) * np.linalg.norm(m))# use np.dot 
print(score)

0.9900436758984326


In [ ]:
#pip install -U scikit-learn

   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 2.0 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/8.7 MB 1.9 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.7 MB 1.8 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.7 MB 1.7 MB/s eta 0:00:05
   --------- ------------------------------ 2.1/8.7 MB 1.8 MB/s eta 0:00:04
   ---------- ----------------------------- 2.4/8.7 MB 1.8 MB/s eta 0:00:04
   ------------- -------------------------- 2.9/8.7 MB 1.8 MB/s eta 0:00:04
   --------------- ------------------------ 3.4/8.7 MB 1.9 MB/s eta 0:00:03
   ---------------- ----------------------- 3.7/8.7 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 4.2/8.7 MB 1.9 MB/s eta 0:00:03
   --------------------- ------------------ 4.7/8.7 MB 1.9 MB/s eta 0:00:03
   -----------------------

In [18]:
# НЕ ТРЕБА ЗАПУСКАТИ
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

docs = [
    "Сьогодні вийшов новий товар станція Ecoflow",
    "Вийшов новий огляд станції Ecoflow",
    "У Києві сьогодні сонячно і тепло",
    "Ecoflow best станція",
    "Люблю сьогодні новий товар який вийшов станція котиків",
    "Сьогодні новий товар вийшов станція котиків"
]

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(docs)
print(X)
cosine_similarity(X[0:1], X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 32 stored elements and shape (6, 15)>
  Coords	Values
  (0, 11)	0.3856547225633519
  (0, 2)	0.3856547225633519
  (0, 6)	0.3856547225633519
  (0, 13)	0.4500454087413492
  (0, 9)	0.3856547225633519
  (0, 1)	0.4500454087413492
  (1, 2)	0.33251546130667675
  (1, 6)	0.33251546130667675
  (1, 1)	0.3880337720277727
  (1, 7)	0.5604893967551546
  (1, 10)	0.5604893967551546
  (2, 11)	0.32403749141635185
  (2, 3)	0.5461988966657346
  (2, 8)	0.5461988966657346
  (2, 12)	0.5461988966657346
  (3, 9)	0.4383997314637185
  (3, 1)	0.5115969669119669
  (3, 0)	0.7389683476976637
  (4, 11)	0.2778328926197939
  (4, 2)	0.2778328926197939
  (4, 6)	0.2778328926197939
  (4, 13)	0.324221150177479
  (4, 9)	0.2778328926197939
  (4, 5)	0.46831623940513917
  (4, 14)	0.46831623940513917
  (4, 4)	0.38402601566888894
  (5, 11)	0.3708198775995746
  (5, 2)	0.3708198775995746
  (5, 6)	0.3708198775995746
  (5, 13)	0.4327336698341691
  (5, 9)	0.3708198775995746
 

array([[1.        , 0.43110513, 0.12496659, 0.39931279, 0.57450451,
        0.76678355]])